# Generated by Django 2.2.10 on 2020-03-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('plain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiopage',
            name='radio_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
