# Generated by Django 2.0.9 on 2018-11-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='mailchimp_api_key',
            field=models.CharField(blank=True, help_text='Maichimp API Key', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='mailchimp_list_id',
            field=models.CharField(blank=True, help_text='Maichimp List ID', max_length=255),
        ),
    ]
