# Generated by Django 2.0.9 on 2018-11-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_auto_20181107_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='mailchimp_api_key',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='mailchimp_list_id',
        ),
    ]
