# Generated by Django 2.0.9 on 2018-12-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_auto_20181222_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='twitter',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='facebook_page',
            field=models.CharField(blank=True, help_text='Full Facebook Page url', max_length=255, verbose_name='Facebook Page'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='instagram_account',
            field=models.CharField(blank=True, help_text='Full Instagram account url', max_length=255, verbose_name='Instagram Account'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter_account',
            field=models.CharField(blank=True, help_text='Full Twitter account url', max_length=255, verbose_name='Twitter Account'),
        ),
    ]
