# Generated by Django 2.0.13 on 2020-01-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('sitesettings', '0006_auto_20181222_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfigurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies_conscent_text', models.CharField(blank=True, help_text='Cookie popup text', max_length=500, verbose_name='Cookie Conscent Text')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
