# Generated by Django 2.2.8 on 2020-01-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0007_generalconfigurations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfigurations',
            name='cookies_conscent_text',
            field=models.CharField(default='This website uses cookies to make your experience better.', help_text='Cookie popup text', max_length=500, verbose_name='Cookie Conscent Text'),
        ),
    ]
