# Generated by Django 2.0.9 on 2018-10-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(default='#000', max_length=7),
        ),
    ]
