# Generated by Django 2.0.9 on 2018-10-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogCategory'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='show_as_featured_in_category',
            field=models.BooleanField(default=False, help_text='Show post as featured in the category BlogPage', verbose_name='show as featured in category'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='show_in_homepage_slider',
            field=models.BooleanField(default=False, help_text='Show post in the main slider of the HomePage', verbose_name='show in homepage slider'),
        ),
    ]
