# Generated by Django 2.0.9 on 2018-10-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181013_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='show_as_featured_in_category',
        ),
    ]
