# Generated by Django 2.0.9 on 2018-10-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blogpage_show_as_featured_in_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
