# Generated by Django 2.0.9 on 2018-10-14 20:24

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181014_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='content_object',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_item', to='blog.BlogPage'),
        ),
    ]
