# Generated by Django 2.0.9 on 2018-10-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_authorsindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorpage',
            name='content_object',
        ),
    ]
