# Generated by Django 2.0.9 on 2018-10-14 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0017_remove_authorpage_content_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorsIndexPage',
            new_name='AuthorIndexPage',
        ),
    ]
