# Generated by Django 2.0.9 on 2018-10-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20181014_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='video',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
