# Generated by Django 2.0.9 on 2018-10-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20181027_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='color',
            new_name='main_color',
        ),
    ]
