# Generated by Django 2.0.9 on 2018-12-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('blog', '0023_auto_20181027_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='mobile_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
