# Generated by Django 2.0.9 on 2018-12-13 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('blog', '0024_blogindexpage_mobile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagetag',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
