# Generated by Django 2.0.9 on 2018-12-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20181213_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='video',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='video_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
