# Generated by Django 2.0.9 on 2018-12-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_blogpage_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
