# Generated by Django 2.0.9 on 2018-12-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_link',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='venue_map_link',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
