# Generated by Django 2.0.9 on 2018-12-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_podcastindexpage_search_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastpage',
            name='description_tag',
            field=models.CharField(default='', max_length=250),
        ),
    ]
