# Generated by Django 2.0.9 on 2018-10-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181014_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
