# Generated by Django 2.0.9 on 2018-12-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_search_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='parallax_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
